services:
  backend:
    image: cronevents-wamp
    environment:
      NODE_ENV: development
      TZ: America/Chicago
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASS: example
      MYSQL_CRON_DB: cron_test
      WAMPURL: ws://localhost:8081/ws
      WAMPREALM: oauth2
      AUTH_DISCOVERY_URI: https://auth.outlawdesigns.io/.well-known/openid-configuration
      AUTH_CLIENT_ID: cronsuite-events
      AUTH_CLIENT_SECRET: 12345
      AUTH_CLIENT_AUDIENCE: wamp-client
      AUTH_CLIENT_SCOPE: "openid, profile, email, roles"
    build:
      context: ./
      dockerfile: ./Dockerfile
